apiVersion: v1
kind: Service
metadata:
  name: fabric-ca
  namespace: fabric-production
spec:
  type: ClusterIP
  ports:
  - port: 7054
    targetPort: 7054
  selector:
    app: fabric-ca
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-fabric-ca
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0f9e4396ff6a917ce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-ca-pvc
  namespace: fabric-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-static-fabric-ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca
  namespace: fabric-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-ca
  template:
    metadata:
      labels:
        app: fabric-ca
    spec:
      containers:
      - name: fabric-ca
        image: hyperledger/fabric-ca:1.4.9
        ports:
        - containerPort: 7054
        - containerPort: 9443
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_METRICS_PROVIDER
          value: prometheus
        - name: FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:9443
        volumeMounts:
          - mountPath: /etc/hyperledger/fabric-ca-server
            name: fabric-ca-server-pvc
          - name: fabric-ca-server-config-yaml
            mountPath: /etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
            subPath: fabric-ca-server-config.yaml
      volumes:
      - configMap:
          name: fabric-ca-server-config
        name: fabric-ca-server-config-yaml
      - persistentVolumeClaim:
          claimName: fabric-ca-pvc
        name: fabric-ca-server-pvc


