apiVersion: v1
kind: Service
metadata:
  name: fabric-peer
  namespace: fabric-production
spec:
  type: ClusterIP
  ports:
  - port: 7051
    name: port-7051
    targetPort: 7051
  - port: 9443
    name: port-9443
    targetPort: 9443
  selector:
    app: fabric-peer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-fabric-peer
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-028935a9a5ddf1d58
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-peer
  namespace: fabric-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-static-fabric-peer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-peer
  namespace: fabric-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-peer
  template:
    metadata:
      labels:
        app: fabric-peer
    spec:
      containers:
      - name: fabric-peer
        image: hyperledger/fabric-peer:2.2.1
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 9443
        env:
          #Generic peer variables
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/crypto-material/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/crypto-material/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/crypto-material/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/fabric/crypto-material/msp/
        # Peer specific variabes
        - name: CORE_PEER_ID
          value: fabric-peer.opensolarx.com
        - name: CORE_PEER_ADDRESS
          value: fabric-peer.opensolarx.com:443
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: fabric-peer.opensolarx.com:443
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: fabric-peer.opensolarx.com:443
        - name: CORE_PEER_LOCALMSPID
          value: opensolarx
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: localhost:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: admin
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: ahtei0loox3O
        - name: CORE_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:9443
        - name: CORE_METRICS_PROVIDER
          value: prometheus
        # - name:
        #   value:
        volumeMounts:
          # - name: cm-configtx-yaml
          #   mountPath: /etc/hyperledger/fabric/configtx.yaml
          #   subPath: configtx.yaml
          - name: opensolarxanchors
            mountPath: /etc/hyperledger/fabric/channel-artifacts/opensolarxanchors.tx
            subPath: emitrasanchors.tx
          - name: emissions-data
            mountPath: /etc/hyperledger/fabric/channel-artifacts/emissions-data.tx
            subPath: emissions-data.tx
          - name: fabric-peer-pvc
            mountPath: /var/hyperledger/production
            subPath: production
          - name: fabric-peer-pvc
            mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer
            subPath: peer
          - name: fabric-peer-pvc
            mountPath: /etc/hyperledger/fabric/crypto-material
            subPath: crypto-material
            # External chaincode builder
          - name: builders-config-core-yaml
            mountPath: /etc/hyperledger/fabric/core.yaml
            subPath: core.yaml
          - name: external-builder-detect
            mountPath: /builders/external/bin/detect
            subPath: detect
          - name: external-builder-build
            mountPath: /builders/external/bin/build
            subPath: build
          - name: external-builder-release
            mountPath: /builders/external/bin/release
            subPath: release

      - name: couchdb
        image: hyperledger/fabric-couchdb:0.4
        ports:
          - containerPort: 5984
          - containerPort: 4369
          - containerPort: 9100
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: ahtei0loox3O
        volumeMounts:
          - mountPath: /opt/couchdb/data
            name: fabric-peer-pvc
            subPath: couchdb-data

      initContainers:
        # Extract and mount crypto-config
        - name: init-container-peer
          image: busybox
          command: ['sh', '-c', 'tar zxvf /etc/peer-secret-tgz/peer-crypto -C /etc/hyperledger/fabric/crypto-material']
          volumeMounts:
              - name: peer-crypto
                mountPath: /etc/peer-secret-tgz
              - name: fabric-peer-pvc
                mountPath: /etc/hyperledger/fabric/crypto-material
                subPath: crypto-material

      volumes:
      - configMap:
          name: opensolarxanchors
        name: opensolarxanchors
      - configMap:
          name: emissions-data
        name: emissions-data
      - secret:
          secretName: peer-crypto
        name: peer-crypto
      - persistentVolumeClaim:
          claimName: fabric-peer
        name: fabric-peer-pvc
      # External chaincode builder
      - name: builders-config-core-yaml
        configMap:
          name: external-chaincode-builder-config
          items:
            - key: core.yaml
              path: core.yaml
      - name: external-builder-detect
        configMap:
          name: external-chaincode-builder-config
          items:
            - key: detect
              path: detect
              mode: 0544
      - name: external-builder-build
        configMap:
          name: external-chaincode-builder-config
          items:
            - key: build
              path: build
              mode: 0544
      - name: external-builder-release
        configMap:
          name: external-chaincode-builder-config
          items:
            - key: release
              path: release
              mode: 0544